// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#r "../../packages/FSharp.Charting.0.90.13/lib/net40/FSharp.Charting.dll"
#r "../../packages/FSharp.Data.2.2.5/lib/net40/FSharp.Data.dll"
#r "../../packages/FSharp.Data.SqlClient.1.7.7/lib/net40/FSharp.Data.SqlClient.dll"
#r "../../packages/SQLProvider.0.0.9-alpha/lib/net40/FSharp.Data.SqlProvider.dll"
#r "System.Core.dll"
#r "System.Data.dll"
#r "System.dll"
#r "System.Numerics.dll"
#r "System.Runtime.Serialization.dll"
#r "System.ServiceModel.dll"
#r "System.Windows.Forms.DataVisualization.dll"
#r "System.Xml.dll"
#r "System.Xml.Linq.dll"
#r "../../packages/FSharp.Data.TypeProviders.5.0.0.2/lib/net40/FSharp.Data.TypeProviders.dll"